const GET_JOBS_REQUEST = 'GET_JOBS_REQUEST';
const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
const GET_JOBS_FAILURE = 'GET_JOBS_FAILURE';

const GET_RECRUITERS_REQUEST = 'GET_RECRUITERS_REQUEST';
const GET_RECRUITERS_SUCCESS = 'GET_RECRUITERS_SUCCESS';
const GET_RECRUITERS_FAILURE = 'GET_RECRUITERS_FAILURE';

export { GET_JOBS_REQUEST, GET_JOBS_SUCCESS, GET_JOBS_FAILURE, GET_RECRUITERS_REQUEST, GET_RECRUITERS_SUCCESS, GET_RECRUITERS_FAILURE };