const GET_JOBS_REQUEST = 'GET_JOBS_REQUEST';
const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
const GET_JOBS_FAILURE = 'GET_JOBS_FAILURE';

const POST_JOBS_REQUEST = 'POST_JOBS_REQUEST';
const POST_JOBS_SUCCESS = 'POST_JOBS_SUCCESS';
const POST_JOBS_FAILURE = 'POST_JOBS_FAILURE';

const GET_RECRUITERS_REQUEST = 'GET_RECRUITERS_REQUEST';
const GET_RECRUITERS_SUCCESS = 'GET_RECRUITERS_SUCCESS';
const GET_RECRUITERS_FAILURE = 'GET_RECRUITERS_FAILURE';

const POST_RECRUITERS_REQUEST = 'POST_RECRUITERS_REQUEST';
const POST_RECRUITERS_SUCCESS = 'POST_RECRUITERS_SUCCESS';
const POST_RECRUITERS_FAILURE = 'POST_RECRUITERS_FAILURE';

const SHOW_ADMIN_DETAILS = 'SHOW_ADMIN_DETAILS';
const HIDE_ADMIN_DETAILS = 'HIDE_ADMIN_DETAILS';

export { GET_JOBS_REQUEST, GET_JOBS_SUCCESS, GET_JOBS_FAILURE, GET_RECRUITERS_REQUEST, GET_RECRUITERS_SUCCESS, GET_RECRUITERS_FAILURE,
        POST_JOBS_REQUEST, POST_JOBS_SUCCESS, POST_JOBS_FAILURE, POST_RECRUITERS_REQUEST, POST_RECRUITERS_SUCCESS, POST_RECRUITERS_FAILURE,
        SHOW_ADMIN_DETAILS, HIDE_ADMIN_DETAILS };