const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

const ADMIN_SIGN_IN_REQUEST = 'ADMIN_SIGN_IN_REQUEST';
const ADMIN_SIGN_IN_SUCCESS = 'ADMIN_SIGN_IN_SUCCESS';
const ADMIN_SIGN_IN_FAILURE = 'ADMIN_SIGN_IN_FAILURE';

const REGISTER_REQUEST = 'REGISTER_REQUEST';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAILURE = 'REGISTER_FAILURE';

const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS';

const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export { SIGN_IN_REQUEST, SIGN_IN_SUCCESS, SIGN_IN_FAILURE, 
    ADMIN_SIGN_IN_REQUEST, ADMIN_SIGN_IN_SUCCESS, ADMIN_SIGN_IN_FAILURE, 
    REGISTER_REQUEST, REGISTER_SUCCESS, REGISTER_FAILURE,
    ADMIN_LOGOUT_SUCCESS, LOGOUT_SUCCESS };