const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST';
const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
const GET_SEARCH_FAILURE = 'GET_SEARCH_FAILURE';

export { GET_SEARCH_REQUEST, GET_SEARCH_SUCCESS, GET_SEARCH_FAILURE }