export const SEND_RESUME_REQUEST = "SEND_RESUME_REQUEST";
export const SEND_RESUME_SUCCESS = "SEND_RESUME_SUCCESS";
export const SEND_RESUME_FAILURE = "SEND_RESUME_FAILURE";

const GET_RESUME_REQUEST = 'GET_RESUME_REQUEST';
const GET_RESUME_SUCCESS = 'GET_RESUME_SUCCESS';
const GET_RESUME_FAILURE = 'GET_RESUME_FAILURE';

const DELETE_RESUME_REQUEST = 'DELETE_RESUME_REQUEST';
const DELETE_RESUME_SUCCESS = 'DELETE_RESUME_SUCCESS';
const DELETE_RESUME_FAILURE = 'DELETE_RESUME_FAILURE';

export { GET_RESUME_REQUEST, GET_RESUME_SUCCESS, GET_RESUME_FAILURE, DELETE_RESUME_REQUEST, DELETE_RESUME_SUCCESS, DELETE_RESUME_FAILURE }