export const MY_JOB_REQUEST = "MY_JOB_REQUEST";
export const MY_JOB_SUCCESS = "MY_JOB_SUCCESS";
export const MY_JOB_FAILURE = "MY_JOB_FAILURE";

export const JOB_DELETE_REQUEST = "JOB_DELETE_REQUEST";
export const JOB_DELETE_SUCCESS = "JOB_DELETE_SUCCESS";
export const JOB_DELETE_FAILURE = "JOB_DELETE_FAILURE";